name: Deploy OpenCTI to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Initialize Terraform
      working-directory: ./azure
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    - name: Validate Terraform
      working-directory: ./azure
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./azure
      run: terraform plan -out=tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

    # - name: Apply Terraform
    #   working-directory: ./azure
    #   run: terraform apply -auto-approve tfplan
    #   env:
    #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #     ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #     ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
    #     TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
    #     TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    #     TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
